-- G Telepathy — Cloudflare D1 Schema (SQLite)
-- Run this in the Cloudflare Dashboard → D1 → your database → Console tab
-- Or via Wrangler CLI: npx wrangler d1 execute gtelepath --file=./d1/schema.sql

-- ─────────────────────────────────────────────────────────────────────────────
-- USERS (self-managed auth — no Supabase)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,                      -- UUID v4 generated by backend
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,              -- bcrypt hash, never plaintext
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    bio TEXT,
    preferred_language TEXT DEFAULT 'en',
    auto_translate INTEGER DEFAULT 1,         -- boolean: 1=true, 0=false
    is_online INTEGER DEFAULT 0,
    last_seen TEXT,                           -- ISO 8601 timestamp
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ─────────────────────────────────────────────────────────────────────────────
-- CONTACTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contacts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    contact_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'blocked')),
    created_at TEXT NOT NULL,
    UNIQUE(user_id, contact_id)
);

CREATE INDEX IF NOT EXISTS idx_contacts_user ON contacts(user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- CONVERSATIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    type TEXT DEFAULT 'direct' CHECK (type IN ('direct', 'group', 'room')),
    name TEXT,
    description TEXT,
    avatar_url TEXT,
    is_encrypted INTEGER DEFAULT 1,           -- always 1 (E2E encrypted)
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_members (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),
    joined_at TEXT NOT NULL,
    UNIQUE(conversation_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_conv_members_user ON conversation_members(user_id);
CREATE INDEX IF NOT EXISTS idx_conv_members_conv ON conversation_members(conversation_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- MESSAGES (E2E Encrypted — server stores ciphertext only)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    encrypted_content TEXT NOT NULL,          -- AES-256 ciphertext, never decrypted server-side
    message_type TEXT DEFAULT 'text' CHECK (message_type IN ('text', 'image', 'file', 'audio', 'system')),
    reply_to TEXT REFERENCES messages(id),
    is_deleted INTEGER DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- GLOBAL ROOMS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rooms (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    topic TEXT,
    language TEXT DEFAULT 'en',
    is_public INTEGER DEFAULT 1,
    member_count INTEGER DEFAULT 0,
    created_by TEXT REFERENCES users(id),
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rooms_public ON rooms(is_public, member_count);
CREATE INDEX IF NOT EXISTS idx_rooms_language ON rooms(language);

CREATE TABLE IF NOT EXISTS room_members (
    id TEXT PRIMARY KEY,
    room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TEXT NOT NULL,
    UNIQUE(room_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_room_members_user ON room_members(user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- CALL LOGS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_logs (
    id TEXT PRIMARY KEY,
    caller_id TEXT REFERENCES users(id),
    callee_id TEXT REFERENCES users(id),
    call_type TEXT CHECK (call_type IN ('audio', 'video')),
    status TEXT CHECK (status IN ('ringing', 'active', 'ended', 'missed')),
    started_at TEXT,
    ended_at TEXT,
    duration_seconds INTEGER,
    translation_enabled INTEGER DEFAULT 0,
    voice_clone_used INTEGER DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_call_logs_caller ON call_logs(caller_id, created_at);
CREATE INDEX IF NOT EXISTS idx_call_logs_callee ON call_logs(callee_id, created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- VOICE CLONE MODELS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS voice_models (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    provider TEXT DEFAULT 'elevenlabs',
    provider_model_id TEXT NOT NULL,
    is_active INTEGER DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_voice_models_user ON voice_models(user_id);
